from django.contrib.auth import get_user_model
from django.test import TestCase
from django.urls import reverse


# Generated by GPT-5.4
class AnalyticsViewTests(TestCase):
    def setUp(self):
        self.url = reverse("exec_panel:analytics:analytics")
        user_model = get_user_model()
        self.exec_user = user_model.objects.create_user(
            username="exec-user",
            password="password123",
            role=user_model.Role.EXEC,
            status=user_model.Status.APPROVED,
        )
        self.member_user = user_model.objects.create_user(
            username="member-user",
            password="password123",
            role=user_model.Role.MEMBER,
            status=user_model.Status.APPROVED,
        )

    def test_anonymous_user_is_redirected_to_login(self):
        response = self.client.get(self.url)

        self.assertRedirects(response, f"/login/?next={self.url}")

    def test_non_exec_user_is_redirected_home(self):
        self.client.force_login(self.member_user)

        response = self.client.get(self.url)

        self.assertRedirects(response, reverse("organization:home"))

    def test_exec_user_sees_user_analytics_by_default(self):
        self.client.force_login(self.exec_user)

        response = self.client.get(self.url)

        self.assertEqual(response.status_code, 200)
        self.assertEqual(response.context["selected_view"], "users")
        self.assertContains(response, "Per-user analytics")
        self.assertContains(response, "Ada Lovelace")
        self.assertContains(response, "Tracked members")

    def test_exec_user_can_switch_to_event_analytics(self):
        self.client.force_login(self.exec_user)

        response = self.client.get(self.url, {"view": "events"})

        self.assertEqual(response.status_code, 200)
        self.assertEqual(response.context["selected_view"], "events")
        self.assertContains(response, "Per-event analytics")
        self.assertContains(response, "Spring Kickoff")
        self.assertNotContains(response, "Ada Lovelace")

    def test_invalid_view_falls_back_to_user_analytics(self):
        self.client.force_login(self.exec_user)

        response = self.client.get(self.url, {"view": "bad"})

        self.assertEqual(response.status_code, 200)
        self.assertEqual(response.context["selected_view"], "users")
        self.assertContains(response, "Per-user analytics")
        self.assertContains(response, "Ada Lovelace")
