from django.contrib.auth.decorators import login_required
from core.decorators import executive_required
from django.shortcuts import render


# Generated by GPT-5.4
def _build_analytics_context(selected_view):
    # TODO: Replace fake analytics data with real attendance and event aggregates once those models exist.
    summary_cards = [
        {"label": "Tracked members", "value": 42},
        {"label": "Tracked events", "value": 8},
        {"label": "Avg attendance", "value": "31"},
    ]
    user_rows = [
        {"name": "Ada Lovelace", "events_attended": 7, "attendance_rate": "88%"},
        {"name": "Grace Hopper", "events_attended": 6, "attendance_rate": "75%"},
        {"name": "Alan Turing", "events_attended": 5, "attendance_rate": "63%"},
    ]
    event_rows = [
        {"name": "Spring Kickoff", "attendees": 37, "engagement": "High"},
        {"name": "Hack Night", "attendees": 33, "engagement": "Medium"},
        {"name": "Resume Workshop", "attendees": 24, "engagement": "High"},
    ]
    normalized_view = selected_view if selected_view in {"users", "events"} else "users"

    return {
        "active_tab": "analytics",
        "summary_cards": summary_cards,
        "selected_view": normalized_view,
        "table_title": "Per-user analytics" if normalized_view == "users" else "Per-event analytics",
        "table_rows": user_rows if normalized_view == "users" else event_rows,
    }


@login_required(login_url="/login/")
@executive_required(redirect_url="organization:home")
def analytics(request):
    context = _build_analytics_context(request.GET.get("view", "users"))

    return render(request, "analytics/analytics.html", context)
