<<<<<<< HEAD
# Generated by Django 6.0.2 on 2026-03-22 02:44

import django.db.models.deletion
import uuid
from django.conf import settings
=======
# Generated by Django 6.0.2 on 2026-03-20 03:46

import uuid
>>>>>>> feature/attendance
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
<<<<<<< HEAD
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
=======
>>>>>>> feature/attendance
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('date', models.DateTimeField()),
<<<<<<< HEAD
                ('description', models.TextField(max_length=2000)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_events', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['date'],
            },
=======
                ('description', models.TextField(blank=True)),
            ],
>>>>>>> feature/attendance
        ),
    ]
