# Generated by GPT-5.4
from django.urls import path

from . import views

app_name = "polls"

urlpatterns = [
    path("<uuid:poll_uid>/", views.poll_detail, name="poll_detail"),
    path("<uuid:poll_uid>/vote/", views.poll_vote, name="poll_vote"),
]
