# Generated by GPT-5.4
from django.contrib.auth.decorators import login_required
from django.db import IntegrityError, transaction
from django.db.models import Count
from django.shortcuts import get_object_or_404, redirect, render
from django.urls import reverse
from django.views.decorators.http import require_POST

from core.decorators import executive_required
from organization.models import Channel, Message

from .forms import PollCreateForm, PollVoteForm
from .models import Poll, PollOption, Vote


def _build_poll_results(poll):
    vote_counts = {
        row["option"]: row["total"]
        for row in poll.votes.values("option").annotate(total=Count("id"))
    }
    total_votes = sum(vote_counts.values())

    return [
        {
            "option": option,
            "votes": vote_counts.get(option.id, 0),
            "percentage": 0 if total_votes == 0 else round((vote_counts.get(option.id, 0) / total_votes) * 100),
        }
        for option in poll.options.all()
    ]


def _announcement_message_text(poll):
    return f"Poll: {poll.question}\nVote here: {reverse('polls:poll_detail', args=[poll.uid])}"


@login_required(login_url="/login/")
@executive_required(redirect_url="organization:home")
def exec_polls(request):
    polls = Poll.objects.prefetch_related("options").all()
    return render(request, "polls/polls.html", {"polls": polls, "active_tab": "polls"})


@login_required(login_url="/login/")
@executive_required(redirect_url="organization:home")
def exec_poll_create(request):
    if request.method == "POST":
        form = PollCreateForm(request.POST)
        if form.is_valid():
            try:
                with transaction.atomic():
                    announcements_channel = Channel.objects.get(name="announcements")
                    poll = Poll.objects.create(
                        question=form.cleaned_data["question"],
                        created_by=request.user,
                    )
                    PollOption.objects.bulk_create(
                        [
                            PollOption(poll=poll, text=option_text, position=index)
                            for index, option_text in enumerate(form.get_options(), start=1)
                        ]
                    )
                    Message.objects.create(
                        channel=announcements_channel,
                        user=request.user,
                        text=_announcement_message_text(poll),
                    )
            except Channel.DoesNotExist:
                form.add_error(None, "The announcements channel is missing.")
            except IntegrityError:
                form.add_error(None, "We could not publish the poll announcement. Please try again.")
            else:
                return redirect("exec_panel:polls:poll_detail", poll.uid)
    else:
        form = PollCreateForm()

    return render(request, "polls/poll_create.html", {"form": form, "active_tab": "polls"})


@login_required(login_url="/login/")
@executive_required(redirect_url="organization:home")
def exec_poll_detail(request, poll_uid):
    poll = get_object_or_404(Poll.objects.prefetch_related("options"), uid=poll_uid)

    return render(
        request,
        "polls/poll_manage.html",
        {
            "poll": poll,
            "active_tab": "polls",
            "results": _build_poll_results(poll),
            "total_votes": poll.votes.count(),
        },
    )


@login_required(login_url="/login/")
@executive_required(redirect_url="organization:home")
@require_POST
def exec_poll_close(request, poll_uid):
    poll = get_object_or_404(Poll, uid=poll_uid)
    poll.close()
    return redirect("exec_panel:polls:poll_detail", poll.uid)


@login_required(login_url="/login/")
def poll_detail(request, poll_uid):
    poll = get_object_or_404(Poll.objects.prefetch_related("options"), uid=poll_uid)
    existing_vote = Vote.objects.filter(poll=poll, user=request.user).select_related("option").first()
    can_view_results = request.user.is_exec() or poll.is_closed
    vote_form = None

    if not poll.is_closed and existing_vote is None:
        vote_form = PollVoteForm(poll)

    context = {
        "poll": poll,
        "existing_vote": existing_vote,
        "can_vote": not poll.is_closed and existing_vote is None,
        "can_view_results": can_view_results,
        "results": _build_poll_results(poll) if can_view_results else None,
        "total_votes": poll.votes.count(),
        "vote_form": vote_form,
    }
    return render(request, "polls/poll_detail.html", context)


@login_required(login_url="/login/")
@require_POST
def poll_vote(request, poll_uid):
    poll = get_object_or_404(Poll.objects.prefetch_related("options"), uid=poll_uid)

    if poll.is_closed:
        return redirect("polls:poll_detail", poll.uid)

    if Vote.objects.filter(poll=poll, user=request.user).exists():
        return redirect("polls:poll_detail", poll.uid)

    form = PollVoteForm(poll, request.POST)
    if form.is_valid():
        try:
            with transaction.atomic():
                Vote.objects.create(
                    poll=poll,
                    option=form.cleaned_data["option"],
                    user=request.user,
                )
        except IntegrityError:
            return redirect("polls:poll_detail", poll.uid)
        return redirect("polls:poll_detail", poll.uid)

    return render(
        request,
        "polls/poll_detail.html",
        {
            "poll": poll,
            "existing_vote": None,
            "can_vote": True,
            "can_view_results": request.user.is_exec(),
            "results": _build_poll_results(poll) if request.user.is_exec() else None,
            "total_votes": poll.votes.count(),
            "vote_form": form,
        },
    )
