# Generated by Django 6.0.2 on 2026-03-22 00:53
# How to make custom data migrations: https://docs.djangoproject.com/en/6.0/topics/migrations/#data-migrations


from django.db import migrations

# get_or_create documentation (suggested by Gemini 3.1 Pro, which also suggested the use of defaults to program more defensively)
# https://docs.djangoproject.com/en/6.0/ref/models/querysets/#django.db.models.query.QuerySet.get_or_create
def create_builtin_channels(apps, schema_editor):
    Channel = apps.get_model("organization", "Channel")

    Channel.objects.get_or_create(
        name="general",
        defaults={
            "exec_only": True,
            "built_in": True
        }
    )

    Channel.objects.get_or_create(
        name="announcements",
        defaults={
            "exec_only": True,
            "built_in": True
        }
    )

class Migration(migrations.Migration):

    dependencies = [
        ("organization", "0001_initial"),
    ]

    operations = [
        migrations.RunPython(create_builtin_channels, migrations.RunPython.noop),
    ]
