# Generated by Django 6.0.2 on 2026-03-28 01:03
# How to make custom data migrations: https://docs.djangoproject.com/en/6.0/topics/migrations/#data-migrations

from django.db import migrations

# update_or_create documentation (suggested by Copilot)
# Additionally, Gemini 3.1 Pro suggested the use of defaults to program more defensively
# https://docs.djangoproject.com/en/6.0/ref/models/querysets/#update-or-create
def create_builtin_channels(apps, schema_editor):
    Channel = apps.get_model("organization", "Channel")

    Channel.objects.update_or_create(
        name="general",
        defaults={
            "exec_only": False,
            "builtin": True
        }
    )

    Channel.objects.update_or_create(
        name="announcements",
        defaults={
            "exec_only": True,
            "builtin": True
        }
    )


class Migration(migrations.Migration):

    dependencies = [
        ("organization", "0001_initial"),
    ]

    operations = [
        migrations.RunPython(create_builtin_channels, migrations.RunPython.noop),
    ]
