# Generated by Django 6.0.2 on 2026-03-22 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("organization", "0002_auto_20260321_2053"),
    ]

    operations = [
        migrations.AlterField(
            model_name="message",
            name="sent_at",
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
