# Generated by Django 6.0.2 on 2026-04-08 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="role",
            field=models.CharField(
                choices=[
                    ("OWNER", "Owner"),
                    ("EXEC", "Exec"),
                    ("MEMBER", "Member"),
                    ("USERADMIN", "Useradmin"),
                ],
                default="MEMBER",
                max_length=20,
            ),
        ),
    ]
