# Generated by Django 6.0.2 on 2026-04-07 04:02
# How to make custom data migrations: https://docs.djangoproject.com/en/6.0/topics/migrations/#data-migrations

from django.db import migrations

def create_deleted_user(apps, schema_editor):
    User = apps.get_model('core', 'User')

    User.objects.update_or_create(
        uid="00000000-0000-0000-0000-000000000000",
        defaults={
            "username": "deleted_user",
            "email": "deleted_user@ciocentral.com",
            "password": "blah",
            "first_name": "Deleted",
            "last_name": "User",
            "is_active": False,
            "status": "BANNED",
            "role": "MEMBER",
        }
    )

class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(create_deleted_user, migrations.RunPython.noop)
    ]