# Generated by Django 6.0.2 on 2026-04-08 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20260407_0002'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('BANNED', 'Banned'), ('DELETED', 'Deleted')], default='PENDING', max_length=20),
        ),
    ]
