# Generated by Django 6.0.2 on 2026-03-11 20:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_add_is_exec'),
        ('core', '0002_add_role_and_status'),
    ]

    operations = [
    ]
