# Generated by Django 6.0.2 on 2026-03-11 20:31

from django.db import migrations


def drop_legacy_membership_and_is_exec(apps, schema_editor):
    connection = schema_editor.connection
    existing_tables = set(connection.introspection.table_names())

    User = apps.get_model('core', 'User')
    user_table = User._meta.db_table
    if user_table in existing_tables:
        with connection.cursor() as cursor:
            columns = {
                column.name
                for column in connection.introspection.get_table_description(
                    cursor, user_table
                )
            }
        if 'is_exec' in columns:
            schema_editor.remove_field(User, User._meta.get_field('is_exec'))

    Membership = apps.get_model('core', 'Membership')
    membership_table = Membership._meta.db_table
    if membership_table in existing_tables:
        schema_editor.delete_model(Membership)


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_merge_0002_add_is_exec_0002_add_role_and_status'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunPython(
                    drop_legacy_membership_and_is_exec,
                    migrations.RunPython.noop,
                ),
            ],
            state_operations=[
                migrations.RemoveField(
                    model_name='user',
                    name='is_exec',
                ),
                migrations.DeleteModel(
                    name='Membership',
                ),
            ],
        ),
    ]
