# Generated by Django 6.0.2 on 2026-04-24 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Organization",
            fields=[
                (
                    "id",
                    models.IntegerField(default=0, primary_key=True, serialize=False),
                ),
                ("name", models.CharField(default="My Organization", max_length=255)),
                (
                    "organization_picture",
                    models.ImageField(
                        blank=True, null=True, upload_to="images/organization-edit/"
                    ),
                ),
            ],
        ),
    ]
