# Generated by Claude Opus 4.6 (verified and edited for correctness)

# custom form to override socialaccount 3rd party signup form defaults
from django import forms
from allauth.socialaccount.forms import SignupForm as SocialSignupForm


class CustomSocialSignupForm(SocialSignupForm):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        if 'email' in self.fields:
            self.fields['email'].widget = forms.HiddenInput()

    def clean_email(self):
        # Prevent tampering — force the initial value from the provider
        email = self.initial.get('email')
        if not email:
            raise forms.ValidationError("Email was not provided by the social account.")
        return email