# Generated by Django 6.0.2 on 2026-04-24 23:45

import core.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='poll',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=models.SET(core.models.get_deleted_user), related_name='created_polls', to=settings.AUTH_USER_MODEL),
        ),
    ]
