# Generated by Django 6.0.2 on 2026-03-20 03:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MyS3Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images/mys3images/')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='my_s3_image', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
