"""
Django settings for project_a_17 project.

Generated by 'django-admin startproject' using Django 6.0.2.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/

Credit to Heroku's Getting Started Project: https://github.com/heroku/python-getting-started/blob/main/gettingstarted/settings.py
for sensible default configurations
"""

import os
import secrets
from pathlib import Path

import dj_database_url

DELETED_USER_UID = "00000000-0000-0000-0000-000000000000"
# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: Keep the secret key used in production secret!
SECRET_KEY = os.environ.get("DJANGO_SECRET_KEY")

# Django has a debug mode which shows more detailed error messages and also means static assets
# can be served without having to run the production `collectstatic` command. However, this
# debug mode *must only be enabled in development* for security and performance reasons:
# https://docs.djangoproject.com/en/6.0/ref/settings/#std-setting-DEBUG
# Debug mode will be automatically enabled when the project is run via `heroku local` (which
# loads the environment variables set in the `.env` file, where `ENVIRONMENT=development`).
# SECURITY WARNING: Don't run with debug turned on in production!
DEBUG = os.environ.get("ENVIRONMENT") == "development"


# The `DYNO` env var is set on Heroku CI, but it's not a real Heroku app, so we have to
# also explicitly exclude CI:
# https://devcenter.heroku.com/articles/heroku-ci#immutable-environment-variables
IS_HEROKU_APP = "DYNO" in os.environ and "CI" not in os.environ

if IS_HEROKU_APP:
    # On Heroku, it's safe to use a wildcard for `ALLOWED_HOSTS`, since the Heroku router performs
    # validation of the Host header in the incoming HTTP request. On other platforms you may need to
    # list the expected hostnames explicitly in production to prevent HTTP Host header attacks. See:
    # https://docs.djangoproject.com/en/6.0/ref/settings/#std-setting-ALLOWED_HOSTS
    ALLOWED_HOSTS = ["*"]

    # Redirect all non-HTTPS requests to HTTPS. This requires that:
    # 1. Your app has a TLS/SSL certificate, which all `*.herokuapp.com` domains do by default.
    #    When using a custom domain, you must configure one. See:
    #    https://devcenter.heroku.com/articles/automated-certificate-management
    # 2. Your app's WSGI web server is configured to use the `X-Forwarded-Proto` headers set by
    #    the Heroku Router (otherwise you may encounter infinite HTTP 301 redirects). See this
    #    app's `gunicorn.conf.py` for how this is done when using gunicorn.
    #
    # For maximum security, consider enabling HTTP Strict Transport Security (HSTS) headers too:
    # https://docs.djangoproject.com/en/6.0/ref/middleware/#http-strict-transport-security
    SECURE_SSL_REDIRECT = True
else:
    ALLOWED_HOSTS = [".localhost", "127.0.0.1", "[::1]", "0.0.0.0", "[::]"]


# Application definition

INSTALLED_APPS = [
    "core.apps.CoreConfig",
    "profiles.apps.ProfilesConfig",
    "exec_panel.apps.ExecPanelConfig",
    "documents.apps.DocumentsConfig",
    "events.apps.EventsConfig",
    "attendance.apps.AttendanceConfig",
    "analytics.apps.AnalyticsConfig",
    "roster.apps.RosterConfig",
    "organization.apps.OrganizationConfig",
    "s3_demo.apps.S3DemoConfig",  # TODO: remove this when done previewing demo
    "django_bootstrap5",
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",

    # The following apps are required for allauth + allauth with social accounts:
    'allauth',
    'allauth.account',
    'allauth.socialaccount',
    # allauth provider (Google)
    'allauth.socialaccount.providers.google',
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "whitenoise.middleware.WhiteNoiseMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
    # allauth account middleware:
    "allauth.account.middleware.AccountMiddleware",
    # redirects non-approved users to /pending/, /rejected/, or /banned/ on every request:
    "core.middleware.ApprovalStatusMiddleware",
]

ROOT_URLCONF = "project_a_17.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [BASE_DIR / 'templates'],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "project_a_17.wsgi.application"


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

if IS_HEROKU_APP:
    # In production on Heroku the database configuration is derived from the `DATABASE_URL`
    # environment variable by the dj-database-url package. `DATABASE_URL` will be set
    # automatically by Heroku when a database addon is attached to your Heroku app. See:
    # https://devcenter.heroku.com/articles/provisioning-heroku-postgres#application-config-vars
    # https://github.com/jazzband/dj-database-url
    DATABASES = {
        "default": dj_database_url.config(
            env="DATABASE_URL",
            conn_max_age=600,
            conn_health_checks=True,
            ssl_require=True,
        ),
    }
else:
    # When running locally in development or in CI, a sqlite database file will be used instead
    # to simplify initial setup. Longer term it's recommended to use Postgres locally too.
    DATABASES = {
        "default": {
            "ENGINE": "django.db.backends.sqlite3",
            "NAME": BASE_DIR / "db.sqlite3",
        }
    }


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "America/New_York"

USE_I18N = True

USE_TZ = True


### Static files (CSS, JavaScript, Images) ###
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_ROOT = BASE_DIR / "staticfiles"
STATIC_URL = "static/"

# I added this so Django and Heroku will collect the compiled CSS custom override file
STATICFILES_DIRS = [
    BASE_DIR / "static",
]

### Bootstrap 5 python package settings ###
BOOTSTRAP5 = {

    # The complete URL to the Bootstrap CSS file.
    # Note that a URL can be either a string
    # ("https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/css/bootstrap.min.css"),
    # or a dict with keys `url`, `integrity` and `crossorigin` like the default value below.
    "css_url": None,

    # The complete URL to the Bootstrap bundle JavaScript file.
    "javascript_url": {
        "url": "https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/js/bootstrap.bundle.min.js",
        "integrity": "sha384-A3rJD856KowSb7dwlZdYEkO39Gagi7vIsF0jrRAoQmDKKtQBHUuLZ9AsSv4jD4Xa",
        "crossorigin": "anonymous",
    },

    # The complete URL to the Bootstrap CSS theme file (None means no theme).
    "theme_url": None,

    # Color mode (None means do not set color mode).
    "color_mode": None,

    # Put JavaScript in the HEAD section of the HTML document (only relevant if you use bootstrap5.html).
    'javascript_in_head': False,

    # Wrapper class for non-inline fields.
    # The default value "mb-3" is the spacing as used by Bootstrap 5 example code.
    'wrapper_class': 'mb-3',

    # Wrapper class for inline fields.
    # The default value is empty, as Bootstrap5 example code doesn't use a wrapper class.
    'inline_wrapper_class': '',

    # Field class for inline fields.
    # the default value is "col-12". This class will combine with `inline_wrapper_class`.
    'inline_field_class': 'col-auto',

    # Label class to use in horizontal forms.
    'horizontal_label_class': 'col-sm-2',

    # Field class to use in horizontal forms.
    'horizontal_field_class': 'col-sm-10',

    # Field class used for horizontal fields without a label.
    'horizontal_field_offset_class': 'offset-sm-2',

    # HTML attributes with any of these prefixes will have underscores converted to hyphens.
    "hyphenate_attribute_prefixes": ["data"],

    # Set placeholder attributes to label if no placeholder is provided.
    'set_placeholder': True,

    # Class to indicate required field (better to set this in your Django form).
    'required_css_class': '',

    # Class to indicate field has one or more errors (better to set this in your Django form).
    'error_css_class': '',

    # Class to indicate success, meaning the field has valid input (better to set this in your Django form).
    'success_css_class': '',

    # Enable or disable Bootstrap 5 server side validation classes (separate from the indicator classes above).
    'server_side_validation': True,

    # Renderers (only set these if you have studied the source and understand the inner workings).
    'formset_renderers':{
        'default': 'django_bootstrap5.renderers.FormsetRenderer',
    },
    'form_renderers': {
        'default': 'django_bootstrap5.renderers.FormRenderer',
    },
    'field_renderers': {
        'default': 'django_bootstrap5.renderers.FieldRenderer',
    },
}

AUTH_USER_MODEL = 'core.User'


### Django allauth settings: ###

# Sources:
# Setup and config:
# https://docs.allauth.org/en/latest/installation/quickstart.html
# https://docs.allauth.org/en/latest/account/configuration.html
# https://docs.allauth.org/en/latest/socialaccount/configuration.html
# https://docs.allauth.org/en/latest/socialaccount/provider_configuration.html

# Good walkthrough (though a bit dated so some stuff is done differently)
# https://www.youtube.com/watch?v=D1B_BkGHbqs

# Views:
# https://docs.allauth.org/en/latest/account/views.html
# https://docs.allauth.org/en/latest/socialaccount/views.html

# How to override the templates:
# https://docs.allauth.org/en/latest/common/templates.html

# Note that this is a general Django setting, but this
AUTHENTICATION_BACKENDS = [
    # Needed to login by username in Django admin, regardless of `allauth`
    'django.contrib.auth.backends.ModelBackend',

    # `allauth` specific authentication methods, such as login by email
    'allauth.account.auth_backends.AuthenticationBackend',
]

# Provider specific settings - TODO: finalize
# https://docs.allauth.org/en/latest/socialaccount/providers/google.html
SOCIALACCOUNT_PROVIDERS = {
    'google': {
        # For each OAuth based provider, either add a ``SocialApp``
        # (``socialaccount`` app) containing the required client
        # credentials, or list them here:
        # NOTE: listing here is preferred since we can store credentials in the environment variables
        'APPS': [
            {
                'client_id': os.environ.get('GOOGLE_CLIENT_ID'),
                'secret': os.environ.get('GOOGLE_CLIENT_SECRET'),
            },
        ],
        'SCOPE': [
            'profile',  # gets basic profile info (name, etc.)
            'email',  # gets the email for the user model
        ],
        'OAUTH_PKCE_ENABLED': True,  # this is set to true for added security
    }
}

# Changed this to only require the email to sign-in (no username needed for Google login)
# This will allow us to bypass the user having to pick a username
# allauth will generate a unique 'username' for the user so the user model field is filled
# this is the simplest way to accomplish this so the admin account is still easy to make and user, but
# actual regular users will not need to provide a username

# Changing these defaults is not necessary as social accounts just get auto-generated usernames
# But if we decide later to add regular accounts, this can allow them to line up with the social accounts
ACCOUNT_SIGNUP_FIELDS = ['email*', 'password1*', 'password2*']  # this setting is necessary since ACCOUNT_LOGIN_METHODS must match this
ACCOUNT_LOGIN_METHODS = {"email"}

# This is set to true as it will disable the normal account functionality since we *only* need Google login
SOCIALACCOUNT_ONLY = True

# specifies where to redirect users on login and logout
LOGIN_REDIRECT_URL = '/'
LOGOUT_REDIRECT_URL = '/'

# Set to none as we are not going to send email verifications (there is not even a configured email server)
ACCOUNT_EMAIL_VERIFICATION = "none"

# This bypasses the additional form to fill in details related to the user model (it creates a unique username, for instance)
# This is the default setting
SOCIALACCOUNT_AUTO_SIGNUP = True


### S3 Settings: ###

# This overrides the default storage for media uploads (from users) to use S3 while keeping staticfiles the same
STORAGES = {
    "default": {
        "BACKEND": "storages.backends.s3.S3Storage",
        "OPTIONS": {
            "access_key": os.environ.get("AWS_S3_ACCESS_KEY_ID"),
            "secret_key": os.environ.get("AWS_S3_SECRET_ACCESS_KEY"),
            "bucket_name": os.environ.get("AWS_STORAGE_BUCKET_NAME"),
            "querystring_expire": 3600,  # if we want to change how long the presigned urls last this is how
            "file_overwrite": False,  # set this to not overwrite files w/ same name and to instead append extra chars
            "region_name": "us-east-1",  # this appears to be unnecessary, but I specified it just in case
        }
    },
    "staticfiles": {
        "BACKEND": "django.contrib.staticfiles.storage.StaticFilesStorage",  # keep staticfiles backend the same
    },
}