# Generated by Django 6.0.2 on 2026-04-08 18:59

import core.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='member',
            field=models.ForeignKey(on_delete=models.SET(core.models.get_deleted_user), to=settings.AUTH_USER_MODEL),
        ),
    ]
